# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shimmy_interface_pb2 as shimmy__interface__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shimmy_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShimmyCloudServiceStub(object):
    """===================================================================
    gRPC Service Definitions
    ===================================================================

    The main service definition for Shimmy's cloud interaction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Communicate = channel.stream_stream(
                '/shimmy.protos.v1.ShimmyCloudService/Communicate',
                request_serializer=shimmy__interface__pb2.RobotToCloudMessage.SerializeToString,
                response_deserializer=shimmy__interface__pb2.CloudToRobotMessage.FromString,
                _registered_method=True)


class ShimmyCloudServiceServicer(object):
    """===================================================================
    gRPC Service Definitions
    ===================================================================

    The main service definition for Shimmy's cloud interaction
    """

    def Communicate(self, request_iterator, context):
        """Bidirectional stream initiated by the robot.
        Robot sends audio chunks and status updates.
        Cloud sends transcriptions, analysis, text responses, and commands.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShimmyCloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Communicate': grpc.stream_stream_rpc_method_handler(
                    servicer.Communicate,
                    request_deserializer=shimmy__interface__pb2.RobotToCloudMessage.FromString,
                    response_serializer=shimmy__interface__pb2.CloudToRobotMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shimmy.protos.v1.ShimmyCloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shimmy.protos.v1.ShimmyCloudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShimmyCloudService(object):
    """===================================================================
    gRPC Service Definitions
    ===================================================================

    The main service definition for Shimmy's cloud interaction
    """

    @staticmethod
    def Communicate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/shimmy.protos.v1.ShimmyCloudService/Communicate',
            shimmy__interface__pb2.RobotToCloudMessage.SerializeToString,
            shimmy__interface__pb2.CloudToRobotMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
